/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clase_04_10;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author narnia
 */
public class FVehiculo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FVehiculo.class.getName());
    public static ArrayList<Vehiculo> vv = new ArrayList<>();
    private DefaultListModel mVehi = new DefaultListModel();
    public static int id;
    /**
     * Creates new form FVehiculo
     */
    public FVehiculo() {
        initComponents();
        this.id=0;
        this.list.setModel(mVehi);
        limpiar();
    }
    
    private void limpiar(){
        den.setText("");
        mar.setText("");
        st.setText("");
        pre.setText("");
        cant.setText("");
    }
    
    private void listado(){
        mVehi.clear();
        for (int i = 0; i < vv.size(); i++) {
            /*
            if(vv.get(i)instanceof Auto){
              mVehi.addElement( ((Auto)vv.get(i)).toString() );
            }else{
              mVehi.addElement( ((Bici)vv.get(i)).toString() );
            }
            */
            mVehi.addElement( vv.get(i).toString() );
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        den = new javax.swing.JTextField();
        mar = new javax.swing.JTextField();
        st = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        cant = new javax.swing.JTextField();
        cam = new javax.swing.JComboBox<>();
        regis = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        total = new javax.swing.JButton();
        caro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Denominacion:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Stock:");

        jLabel4.setText("Precio:");

        c.setText("C.Puertas:");

        den.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denActionPerformed(evt);
            }
        });

        cam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Bici" }));
        cam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                camItemStateChanged(evt);
            }
        });

        regis.setText("Registrar");
        regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisActionPerformed(evt);
            }
        });

        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list);

        total.setText("Importe Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        caro.setText("Vehiculo mas caro");
        caro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(pre))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                    .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(den, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(c)
                                .addGap(18, 18, 18)
                                .addComponent(cant))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cam, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(regis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(den, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(caro)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regis))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(st, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c)
                    .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void denActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_denActionPerformed

    private void camItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_camItemStateChanged
       if(cam.getSelectedItem().equals("Auto")){
           c.setText("C.Puertas");
       }else   c.setText("C.Cambios");
    }//GEN-LAST:event_camItemStateChanged

    private void regisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisActionPerformed
        Vehiculo aux=null;
        if(cam.getSelectedItem().equals("Auto")){
           aux = new Auto(this.den.getText(), 
                   this.mar.getText(), 
                   Integer.parseInt(this.st.getText()), 
                   Integer.parseInt(this.pre.getText()), 
                   this.id, 
                   Integer.parseInt(this.cant.getText()));
            
       }else{
            aux = new Bici(this.den.getText(), 
                   this.mar.getText(), 
                   Integer.parseInt(this.st.getText()), 
                   Integer.parseInt(this.pre.getText()), 
                   this.id, 
                   Integer.parseInt(this.cant.getText()));
        }
        
        id++;
        vv.add(aux);
        limpiar();
        listado();
        
    }//GEN-LAST:event_regisActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        int impA=0;
        int impB=0;
        for (int i = 0; i < vv.size(); i++) {
            
            if(vv.get(i)instanceof Auto){
              impA+=vv.get(i).getStock()*vv.get(i).getPrecio();
            }else{
              impB+=vv.get(i).getStock()*vv.get(i).getPrecio();
            }
        }
        JOptionPane.showMessageDialog(null, "Importe Total\nAutos:  "+impA+"\nBicis:    "+impB);
    }//GEN-LAST:event_totalActionPerformed

    private void caroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caroActionPerformed
        int bc=-1;
        int ac=-1;
       
        for (int i = 0; i < vv.size(); i++) {
            
            if(vv.get(i)instanceof Auto){
                
              if(ac==-1){
                  ac=i;
              }else{
                  if(vv.get(i).getPrecio()>vv.get(ac).getPrecio())  ac=i;
              }
              
            }else{
                
              if(bc==-1){
                  bc=i;
              }else{
                  if(vv.get(i).getPrecio()>vv.get(bc).getPrecio())  bc=i;
              }
              
            }
        
        }
        
        String a="Vehiculos mas caros";
        a+="\nAuto mas caro:    ";
        if(ac==-1)  a+="No hay registro";
        else{
            for (int i = 0; i < vv.size(); i++) {
                if(vv.get(i).getPrecio()==vv.get(ac).getPrecio() && vv.get(i)instanceof Auto)   a+=vv.get(i).toString();
            }
        }
        a+="\nBici mas cara:    ";
        if(bc==-1)  a+="No hay registro";
        else{
            for (int i = 0; i < vv.size(); i++) {
                if(vv.get(i).getPrecio()==vv.get(bc).getPrecio() && vv.get(i)instanceof Bici)   a+=vv.get(i).toString();
            }
        }
        JOptionPane.showMessageDialog(null, a);
    }//GEN-LAST:event_caroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FVehiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c;
    private javax.swing.JComboBox<String> cam;
    private javax.swing.JTextField cant;
    private javax.swing.JButton caro;
    private javax.swing.JTextField den;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField mar;
    private javax.swing.JTextField pre;
    private javax.swing.JButton regis;
    private javax.swing.JTextField st;
    private javax.swing.JButton total;
    // End of variables declaration//GEN-END:variables
}
